version: "3.7"

# single node elasticsearch
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    volumes:
        - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.6.1
      environment:
        - ELASTICSEARCH_HOST=http://elasticsearch:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

volumes:
    elasticsearch-data-volume:
        driver: local