version: "3.7"

# single node elasticsearch
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    volumes:
        - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.2.3
      environment:
        - ELASTICSEARCH_HOST=http://elasticsearch:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

  postgres:
      image: postgres:latest
      restart: always
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "username" ]
        timeout: 45s
        interval: 10s
        retries: 10
      container_name: postgres
      ports:
        - 5432:5432
      # Import the data from local csv file
      volumes:
        - ./pg_data:/var/lib/pg_data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      env_file:
      - .env

volumes:
    elasticsearch-data-volume:
        driver: local